---
- hosts: all
  sudo: yes
  tasks:
    - apt: upgrade=dist
    - apt: update_cache=yes
    - apt: name=build-essential state=present
    - apt: name=libssl-dev state=present force=yes
    - apt: name=libffi-dev state=present force=yes
    - apt: name=python-dev state=present force=yes
    - apt: name=python-pip state=present force=yes
    - pip: name=pexpect state=present extra_args="--upgrade"
    - pip: name=caravel
      failed_when: false
    - expect:
        command: fabmanager create-admin --app caravel
        responses:
          (?i)Username [admin] "admin"
          (?i)User first name [admin] "admin"
          (?i)User last name [user] "admin"
          (?i)Email [admin@fab.org] "admin"
          (?i)Password "admin"
          (?i)Repeat for confirmation "admin"
    - copy: src=../zika.db dest=/zika.db force=yes
    - shell: caravel db upgrade
    - shell: caravel init
    - shell: caravel runserver
