---
- hosts: all
  sudo: yes
  tasks:
    - apt: upgrade=dist
    - apt: update_cache=yes
    - apt: name=build-essential state=present
    - apt: name=libssl-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=python-dev state=present
    - apt: name=python-pip state=present
    - copy: src=../zika.db dest=/zika.db force=yes
    - copy: src=../caravel.sh dest=/caravel.sh force=yes
    - shell: apt-get install -y python-pip --force-yes
    - shell: pip install caravel
      failed_when: false
    - expect:
        command: fabmanager create-admin --app caravel
        responses:
          (?i)password: "MySekretPa$$word"
    - shell: caravel db upgrade
    - shell: caravel init
    - shell: caravel runserver
