---
- hosts: all
  sudo: yes
  pre_tasks:
      ignore_errors: True
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: installing caravel
      command: sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip
      command: sudo pip install caravel
      command: fabmanager create-admin --app caravel
      command: caravel db upgrade
      command: caravel init
      command: caravel runserver -p 8088
    - name: Download Zika DB from the repo
      command: wget https://github.com/DylanAlloy/UnicornBreakfast/blob/master/zika.db
