---
- hosts: all
  sudo: yes
  tasks:
    - apt: upgrade=dist
    - apt: update_cache=yes
    - apt: name=build-essential state=present
    - apt: name=libssl-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=python-dev state=present
    - apt: name=python-pip state=present
    - copy: src=../zika.db dest=/zika.db force=yes
    - copy: src=../caravel.py dest=/caravel.py force=yes
    - command: sudo python /caravel.py
      failed_when: false
