---
- hosts: all
  sudo: yes
  tasks:
    - apt: upgrade=dist
    - apt: update_cache=yes
    - apt: name=build-essential state=present
    - apt: name=libssl-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=python-dev state=present
    - apt: name=python-pip state=present
    - pip: name=caravel
    - copy: src=~/Desktop/UnicornBreakfast-master/zika.db dest=zika.db
      failed_when: false
