---
- hosts: all
  sudo: yes
  tasks:
    - apt: upgrade=dist
    - apt: update_cache=yes
    - apt: name=build-essential state=present
    - apt: name=libssl-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=python-dev state=present
    - apt: name=python-pip state=present
    - copy: src=../zika.db dest=/zika.db force=yes
    - shell: pip install -y caravel --force-yes
      failed_when: false
