---
- hosts: all
  sudo: yes
  tasks:
    - apt: upgrade=dist
    - apt: update_cache=yes
    - apt: name=build-essential state=present
    - apt: name=libssl-dev state=present force=yes
    - apt: name=libffi-dev state=present force=yes
    - apt: name=python-dev state=present force=yes
    - apt: name=python-pip state=present force=yes
    - pip: name=pexpect state=present extra_args="--upgrade"
    - pip: name=caravel
      failed_when: false
    - copy: src=../zika.db dest=/zika.db force=yes
    - copy: src=../caravel.db dest=/tmp/caravel.db force=yes
    - shell: caravel db upgrade
    - shell: caravel init
    - shell: caravel runserver
